run:
    timeout: 5m

linters:
    enable:
        - errcheck
        - gosimple
        - govet
        - staticcheck
        - unused

issues:
    exclude-rules:
        -   path: _test\.go
            linters:
                - errcheck
