name: Linux Build

on:
    workflow_dispatch: # Enable manual execution

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            -   name: Checkout Repository
                uses: actions/checkout@v4

            # Set up Go
            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.23

            # Install dependencies and run the tests
            -   name: Install Dependencies
                run: |
                    sudo apt-get install -y make
                    make test
                continue-on-error: false

            # Build the application
            -   name: Build for Linux
                run: |
                    make build
                continue-on-error: false

            # Debug: List Build Directory
            -   name: List Build Directory
                run: ls -R bin

            # Upload Build Artifact
            -   name: Upload Build Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: template-go-project-linux-amd64
                    path: 'bin/template-go-project'
