name: Windows Build

on:
  workflow_dispatch: { } # Allow manual execution

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Rust
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      # Install dependencies and run the tests
      - name: Install Dependencies
        run: |
          choco install make -y
          make test
        continue-on-error: false

      # Build the application
      - name: Build for Windows
        run: |
          make build
        continue-on-error: false

      # Debug: List Build Directory
      - name: List Build Directory
        run: ls -R target

      # Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: template-rust-project-windows-amd64
          path: 'target/release/template-rust-project.exe'