name: Publish to Crates.io

on:
  workflow_dispatch: { } # Allow manual execution
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Verify Git State
        run: |
          git status
          git diff --exit-code || (echo "Uncommitted changes detected!" && exit 1)

      - name: Run Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make test
        continue-on-error: false

      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --token $CARGO_REGISTRY_TOKEN
        continue-on-error: false