name: Build and Release

on:
    workflow_dispatch: # Allow manual execution
    push:
        tags:
            - 'v*' # Trigger on version tags

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.23

            -   name: Install Dependencies
                run: |
                    choco install make -y
                    make test

            -   name: Build Windows Binary
                run: |
                    make build PROJ_BINARY=template-go-project.exe

            -   name: Upload Windows Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: template-go-project-windows
                    path: bin/template-go-project.exe

    build-linux:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.23

            -   name: Install Dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y make
                    make test

            -   name: Build Linux Binary
                run: |
                    make build

            -   name: Upload Linux Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: template-go-project-linux
                    path: bin/template-go-project

    build-macos:
        runs-on: macos-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.23

            -   name: Install Dependencies
                run: |
                    brew install make
                    make test

            -   name: Build macOS Binary
                run: |
                    make build-macos

            -   name: Upload macOS Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: template-go-project-macos
                    path: bin/template-go-project

    release:
        runs-on: ubuntu-latest
        needs: [ build-windows, build-linux, build-macos ]
        steps:
            -   name: Download Windows Artifact
                uses: actions/download-artifact@v4
                with:
                    name: template-go-project-windows
                    path: ./windows

            -   name: Download Linux Artifact
                uses: actions/download-artifact@v4
                with:
                    name: template-go-project-linux
                    path: ./linux

            -   name: Download macOS Artifact
                uses: actions/download-artifact@v4
                with:
                    name: template-go-project-macos
                    path: ./macos

            -   name: List Downloaded Files (for debugging)
                run: ls -R .

            -   name: Rename Extracted Binaries
                run: |
                    cd windows && zip -r9 ../template-go-project-windows-amd64.zip template-go-project.exe && cd ..
                    cd linux && zip -r9 ../template-go-project-linux-amd64.zip template-go-project && cd ..
                    cd macos && zip -r9 ../template-go-project-macos-universal.zip template-go-project && cd ..

            -   name: Create GitHub Release
                uses: ncipollo/release-action@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    name: ${{ github.ref_name }}
                    tag: ${{ github.ref_name }}
                    body: |
                        Release version ${{ github.ref_name }}
                        - Binary builds for Windows, Linux, and macOS
                    artifacts: |
                        template-go-project-windows-amd64.zip
                        template-go-project-linux-amd64.zip
                        template-go-project-macos-universal.zip
                    draft: false
                    prerelease: false
