name: Run Tests

on:
  workflow_dispatch:
  schedule: # Run every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_call:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Define the Rust versions to test against
        rust-version: [ "1.92.0", "stable" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-deps

      - name: Run tests and generate coverage report
        run: make coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: false
